name: ddd_firebase
description: "A new Flutter project using DDD architect and connect firebase"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  Style
  cupertino_icons: ^1.0.6
  file_icon: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  video_thumbnail: ^0.5.3
  easy_stepper: ^0.8.5
  mask_text_input_formatter: ^2.9.0
  email_validator: ^3.0.0
  intl_phone_field: ^3.2.0
  timer_count_down: ^2.2.2
  cached_network_image: ^3.4.0
  iphone_has_notch: ^1.0.0
  blurrycontainer: ^2.1.0
  flutter_vector_icons: ^2.0.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  country_flags: ^3.0.0
  flutter_otp_text_field: ^1.1.3+2
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  keyboard_dismisser: ^3.0.0
  device_preview: ^1.2.0
  l: ^4.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  pinput: ^5.0.0


#  State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

#  Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.2
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0


#   Routing
  go_router: ^14.6.0

#  Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  http: ^1.2.2

#  Locale
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11



flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
