// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5LfJxukYErnWC-8GOe2UeUmNg1hoeXk',
    appId: '1:1089185347598:web:49575ac389403abe24245f',
    messagingSenderId: '1089185347598',
    projectId: 'myproject-91c3b',
    authDomain: 'myproject-91c3b.firebaseapp.com',
    storageBucket: 'myproject-91c3b.firebasestorage.app',
    measurementId: 'G-QJ3HM1BFKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcG3DHziMu_yjqmeSxG2Mt4xpO4W-rupw',
    appId: '1:1089185347598:android:b94d14dee6593fba24245f',
    messagingSenderId: '1089185347598',
    projectId: 'myproject-91c3b',
    storageBucket: 'myproject-91c3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTLcA-TYEZDZPVfPy0QtKbXyEpAa9tZdw',
    appId: '1:1089185347598:ios:ac747da61ced0f5724245f',
    messagingSenderId: '1089185347598',
    projectId: 'myproject-91c3b',
    storageBucket: 'myproject-91c3b.firebasestorage.app',
    iosBundleId: 'com.example.dddFirebase',
  );
}
